### ISSUE TITLE
Basic example

### ISSUE THREAD

**Issue by YusufBesim** [sukesh-ak/LVGL8-WT32-SC01-Arduino#3]
Hello,

When i use basic example successfully flash and boot but screen is not starting.

`
/*
    Simple Touch Drawing sample for WT32-SC01
*/
#define LGFX_AUTODETECT     // Autodetect board
#define LGFX_USE_V1         // set to use new version of library

#include <LovyanGFX.hpp>    // main library

static LGFX lcd;            // declare display variable

// Variables for touch x,y
static int32_t x,y;

void setup(void)
{
  lcd.init();

  // Setting display to landscape
  if (lcd.width() < lcd.height()) lcd.setRotation(lcd.getRotation() ^ 1);

  lcd.setCursor(0,0);
  lcd.printf("Ready to touch & draw!");
}

void loop()
{
  if (lcd.getTouch(&x, &y)) {
    lcd.fillRect(x-2, y-2, 5, 5, TFT_RED);
    lcd.setCursor(380,0);
    lcd.printf("Touch:(%03d,%03d)", x,y);
  }
}
`

**platform.io.ini**

[env:esp32dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps = 
	bblanchon/ArduinoJson@^6.20.0
	ottowinter/ESPAsyncWebServer-esphome@^3.0.0
	lovyan03/LovyanGFX@^1.1.2
monitor_speed = 115200
board_upload.flash_size = 16MB
board_build.flash_mode = dio
build_flags = 
	-D CONFIG_ESP32_PSRAM_ENABLE=1
	-D ARDUINO_USB_CDC_ON_BOOT

Thanks for this repo

**Comment by sukesh-ak** [comment]
Please check the latest project here. This one is not maintained anymore.
https://github.com/sukesh-ak/ESP32-TUX
